### ISSUE TITLE
Parsing exception for empty multiline strings

### ISSUE THREAD

**Issue by njalerikson** [hjson/hjson-py#14]
Empty multiline strings are not being parsed correctly:

```python
import hjson

hjson.loads("""

hello: ""

""")
# OrderedDict([('hello', '')])

hjson.loads("""

hello: ''

""")
# OrderedDict([('hello', '')])

hjson.loads("""

hello: ''''''

""")
# Traceback (most recent call last):
# ...
# File "/hpcdata/odkuuf/ENV_CONDA/BEAVER/dev/lib/python3.6/site-packages/hjson/decoder.py", line 203, in mlscanstring
#     if string[-1] == '\n':
# IndexError: string index out of range

hjson.loads("""

hello: '''
'''

""")
# Traceback (most recent call last):
# ...
# File "/hpcdata/odkuuf/ENV_CONDA/BEAVER/dev/lib/python3.6/site-packages/hjson/decoder.py", line 203, in mlscanstring
#     if string[-1] == '\n':
# IndexError: string index out of range


hjson.loads("""

hello: '''

'''

""")
# OrderedDict([('hello', '')])
```

**Comment by laktak** [comment]
Sorry, this project is EOL, see https://hjson.org
