### ISSUE TITLE
Claimed to support py27, fails to install

### ISSUE THREAD

**Issue by bashu** [hjson/hjson-py#34]
```shell
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting hjson
  Downloading hjson-3.1.0.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 1.0 MB/s
    ERROR: Command errored out with exit status 1:
     command: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jt/83jw43hn0nl97jgxmswvvdh40000gn/T/pip-install-raiNzN/hjson/setup.py'"'"'; __file__='"'"'/private/var/folders/jt/83jw43hn0nl97jgxmswvvdh40000gn/T/pip-install-raiNzN/hjson/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jt/83jw43hn0nl97jgxmswvvdh40000gn/T/pip-pip-egg-info-y1eBgO
         cwd: /private/var/folders/jt/83jw43hn0nl97jgxmswvvdh40000gn/T/pip-install-raiNzN/hjson/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jt/83jw43hn0nl97jgxmswvvdh40000gn/T/pip-install-raiNzN/hjson/setup.py", line 80
        **kw,
            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by asukaminato0721** [comment]
`**kw,` to `**kw`

---

![image](https://github.com/hjson/hjson-py/assets/30024051/238faacc-4d5e-4515-b252-f8a50228054a)

![image](https://github.com/hjson/hjson-py/assets/30024051/517f1311-d5b6-471f-93af-0dd2b8d2d267)
